// In-memory prototype "database". Resets on server restart.

export type FieldKey =
  | 'brandName'
  | 'beverageType'
  | 'classType'
  | 'abv'
  | 'netContents'
  | 'bottlerAddress'
  | 'countryOfOrigin'
  | 'governmentWarning'

export const FIELD_LABELS: Record<FieldKey, string> = {
  brandName: 'Brand Name',
  beverageType: 'Beverage Type',
  classType: 'Class / Type Designation',
  abv: 'Alcohol Content (ABV)',
  netContents: 'Net Contents',
  bottlerAddress: 'Name & Address of Bottler/Producer',
  countryOfOrigin: 'Country of Origin',
  governmentWarning: 'Government Health Warning Statement',
}

export interface ApplicationData {
  brandName: string
  /** Broad federal category — "Wine", "Distilled Spirits", or "Malt
   * Beverage" — as distinct from the more specific classType designation
   * (e.g. "Straight Bourbon Whiskey"). Compared like any other field. */
  beverageType: string
  classType: string
  abv: string
  netContents: string
  bottlerAddress: string
  /** null for domestic products — this field only applies to imports. */
  countryOfOrigin: string | null
  governmentWarning: string
}

export type AppStatus = 'Pending' | 'Needs Review' | 'Approved' | 'Flagged'

/** 'onLabel' is a neutral, non-judged state used for fields (currently just
 * classType) where we only confirm presence on the label rather than
 * compare wording against the application — see server/compare.ts.
 * 'missing' is distinct from both 'mismatch' (a value was detected and it
 * disagrees with the application) and 'unreadable' (a value is there but
 * image quality prevents reading it) — it means the field is genuinely not
 * printed on the label at all. Kept as its own status rather than folded
 * into 'mismatch' so the UI doesn't imply a wrong value was found when
 * really nothing was found. */
export type FieldStatus = 'match' | 'variance' | 'mismatch' | 'unreadable' | 'onLabel' | 'missing'

export interface FieldResult {
  key: FieldKey
  label: string
  appValue: string
  detected: string
  status: FieldStatus
  highStakes?: boolean
  note?: string
}

export interface ReviewResult {
  fields: FieldResult[]
  imageQuality: 'clear' | 'poor'
  qualityNote?: string
  reviewedAt: string
  /** True when this review was generated by the local mock extractor
   * instead of a live Claude API call (see server/mock.ts). */
  mockMode?: boolean
  /** How long the extraction call itself took, in ms — shown to the
   * reviewer so analysis speed isn't a black box. */
  durationMs?: number
}

export interface Decision {
  action: 'approve' | 'reject' | 'flag'
  comment: string
  at: string
}

export interface Application {
  id: string
  brand: string
  type: string
  submitted: string
  status: AppStatus
  flagged: number
  applicationData: ApplicationData
  labelImageDataUrl?: string
  review?: ReviewResult
  decision?: Decision
}

const GOVERNMENT_WARNING =
  'GOVERNMENT WARNING: (1) ACCORDING TO THE SURGEON GENERAL, WOMEN SHOULD NOT DRINK ALCOHOLIC BEVERAGES DURING PREGNANCY BECAUSE OF THE RISK OF BIRTH DEFECTS. (2) CONSUMPTION OF ALCOHOLIC BEVERAGES IMPAIRS YOUR ABILITY TO DRIVE A CAR OR OPERATE MACHINERY, AND MAY CAUSE HEALTH PROBLEMS.'

export const STATUTORY_GOVERNMENT_WARNING = GOVERNMENT_WARNING

const seed: Application[] = [
  {
    id: 'A-00412', brand: 'Barefoot Cellars', type: 'Table Wine', submitted: 'Jul 28', status: 'Needs Review', flagged: 0,
    labelImageDataUrl: '/labels/barefoot-cellars.jpg',
    applicationData: {
      brandName: 'Barefoot Cellars',
      classType: 'Pinot Grigio',
      beverageType: 'Wine',
      abv: '12.5% ALC BY VOL',
      netContents: '750 mL',
      bottlerAddress: 'Barefoot Cellars, Modesto, CA 95354',
      countryOfOrigin: null,
      governmentWarning: GOVERNMENT_WARNING,
    },
  },
  {
    id: 'A-00410', brand: 'Sierra Nevada Brewing Co.', type: 'Pale Ale', submitted: 'Jul 27', status: 'Needs Review', flagged: 0,
    labelImageDataUrl: '/labels/sierra-nevada.jpg',
    applicationData: {
      brandName: 'Sierra Nevada Brewing Co.',
      classType: 'Pale Ale',
      beverageType: 'Malt Beverage',
      abv: '5.6% ALC BY VOL',
      netContents: '355 mL',
      bottlerAddress: 'Sierra Nevada Brewing Co., Chico, CA & Mills River, NC',
      countryOfOrigin: null,
      governmentWarning: GOVERNMENT_WARNING,
    },
  },
  {
    id: 'A-00409', brand: 'Jose Cuervo', type: 'Tequila Reposado (Import)', submitted: 'Jul 27', status: 'Needs Review', flagged: 0,
    labelImageDataUrl: '/labels/jose-cuervo.jpg',
    applicationData: {
      brandName: 'Jose Cuervo',
      classType: 'Tequila Reposado',
      beverageType: 'Distilled Spirits',
      abv: '40% ALC BY VOL',
      netContents: '700 mL',
      bottlerAddress: '"La Rojeña" Jose Cuervo No. 73, Tequila, Jalisco, 46400 Mexico',
      countryOfOrigin: 'Mexico',
      governmentWarning: GOVERNMENT_WARNING,
    },
  },
  {
    id: 'A-00407', brand: 'Korbel Champagne Cellars', type: 'Sparkling Wine', submitted: 'Jul 25', status: 'Needs Review', flagged: 0,
    labelImageDataUrl: '/labels/korbel.jpg',
    applicationData: {
      brandName: 'Korbel Champagne Cellars',
      classType: 'California Champagne (Brut)',
      beverageType: 'Wine',
      abv: '12% ALC BY VOL',
      netContents: '750 mL',
      bottlerAddress: 'F. Korbel & Bros., Inc., Guerneville, Sonoma Co., California',
      countryOfOrigin: null,
      governmentWarning: GOVERNMENT_WARNING,
    },
  },
  {
    id: 'A-00406', brand: "Tito's Handmade Vodka", type: 'Vodka', submitted: 'Jul 25', status: 'Needs Review', flagged: 0,
    labelImageDataUrl: '/labels/titos.jpg',
    applicationData: {
      brandName: "Tito's Handmade Vodka",
      classType: 'Vodka',
      beverageType: 'Distilled Spirits',
      abv: '40% ALC BY VOL',
      netContents: '1 L',
      bottlerAddress: 'Fifth Generation Inc., Austin, TX 78744',
      countryOfOrigin: null,
      governmentWarning: GOVERNMENT_WARNING,
    },
  },
  {
    id: 'A-00404', brand: 'Bacardi', type: 'Rum, 151 Proof', submitted: 'Jul 24', status: 'Needs Review', flagged: 0,
    labelImageDataUrl: '/labels/bacardi.jpg',
    applicationData: {
      brandName: 'Bacardi',
      classType: 'Rum',
      beverageType: 'Distilled Spirits',
      abv: '75.5% ALC BY VOL',
      netContents: '750 mL',
      bottlerAddress: 'Bacardi Corporation, San Juan, P.R.',
      countryOfOrigin: null,
      governmentWarning: GOVERNMENT_WARNING,
    },
  },
  {
    id: 'A-00413', brand: 'Grey Goose', type: 'Vodka (Import)', submitted: 'Jul 29', status: 'Needs Review', flagged: 0,
    labelImageDataUrl: '/labels/grey-goose.jpg',
    applicationData: {
      brandName: 'Grey Goose',
      classType: 'Vodka',
      beverageType: 'Distilled Spirits',
      abv: '40% ALC/VOL',
      netContents: '700 mL',
      bottlerAddress: 'Grey Goose, BMP, 11 Route du Laubarde, 16130 Gensac-la-Pallue, France',
      countryOfOrigin: 'France',
      governmentWarning: GOVERNMENT_WARNING,
    },
  },
  {
    id: 'A-00414', brand: 'Clase Azul', type: 'Tequila Blanco (Import)', submitted: 'Jul 29', status: 'Needs Review', flagged: 0,
    labelImageDataUrl: '/labels/clase-azul.jpg',
    applicationData: {
      brandName: 'Clase Azul',
      classType: 'Tequila Blanco',
      beverageType: 'Distilled Spirits',
      abv: '45% ALC BY VOL',
      netContents: '750 mL',
      bottlerAddress: 'Imported by Tequilas Premium, Inc., San Francisco, CA',
      countryOfOrigin: 'Mexico',
      governmentWarning: GOVERNMENT_WARNING,
    },
  },
  {
    id: 'A-00415', brand: 'Johnnie Walker Blue Label', type: 'Blended Scotch Whisky (Import)', submitted: 'Jul 29', status: 'Needs Review', flagged: 0,
    labelImageDataUrl: '/labels/johnnie-walker-blue-label.jpg',
    applicationData: {
      brandName: 'Johnnie Walker Blue Label',
      classType: 'Blended Scotch Whisky',
      beverageType: 'Distilled Spirits',
      abv: '40% ALC/VOL',
      netContents: '750 mL',
      bottlerAddress: 'John Walker & Sons, Kilmarnock, Scotland',
      countryOfOrigin: 'Scotland',
      governmentWarning: GOVERNMENT_WARNING,
    },
  },
  {
    id: 'A-00416', brand: "Trader Joe's", type: 'Pinot Noir', submitted: 'Jul 30', status: 'Needs Review', flagged: 0,
    labelImageDataUrl: '/labels/trader-joes-pinot-noir.jpg',
    applicationData: {
      brandName: "Trader Joe's",
      classType: 'Pinot Noir',
      beverageType: 'Wine',
      abv: '13.7% ALC BY VOL',
      netContents: '750 mL',
      bottlerAddress: 'Cultavin Cellars, Dundee, OR',
      countryOfOrigin: null,
      governmentWarning: GOVERNMENT_WARNING,
    },
  },
]

export const applications = new Map<string, Application>(seed.map(a => [a.id, a]))

export function listApplications(): Application[] {
  return [...applications.values()].sort((a, b) => (a.submitted < b.submitted ? 1 : -1))
}

export function getApplication(id: string): Application | undefined {
  return applications.get(id)
}
